name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/rails_test
    steps:
      - name: Install fonts-noto-cjk
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto-cjk

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: bin/rails assets:precompile

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run RSpec
        run: bundle exec rspec
        id: run-rspec

      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tmp/capybara
        if: failure() && steps.run-rspec.outcome == "failure"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
        if: steps.run-rspec.outcome == "success" || (failure() && steps.run-rspec.outcome == "failure")

  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run RuboCop
        run: bundle exec rubocop
        id: run-rubocop

      - name: Run ESLint
        run: yarn run eslint app/javascript
        id: run-eslint
        if: steps.run-rubocop.outcome == "success" || (failure() && steps.run-rubocop.outcome == "failure")

      - name: Run Prettier
        run: yarn run prettier --check app/assets/stylesheets app/javascript
        if: steps.run-eslint.outcome == "success" || (failure() && steps.run-eslint.outcome == "failure")
