name: Rails Edge

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
    env:
      BUNDLE_GEMFILE: gemfiles/rails_edge.gemfile
      RAILS_ENV: test
    steps:
      - name: Install fonts-noto-cjk
        run: |
          sudo apt-get update
          sudo apt-get install fonts-noto-cjk

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: bin/rails assets:precompile

      - name: Create db and loads schema
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails parallel:setup

      - name: Run RSpec
        run: bin/rails parallel:spec
        id: run-rspec
        continue-on-error: true

      - name: Archive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: tmp/capybara
        if: failure() && steps.run-rspec.outcome == 'failure'

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
        if: steps.run-rspec.outcome == 'success' || (failure() && steps.run-rspec.outcome == 'failure')
